from pydantic import BaseModel, Field


class InquiryRequest(BaseModel):
    userId: str = Field(..., min_length=1, description="Unique identifier for the user")
    message: str = Field(..., min_length=1, description="Raw message that may contain PII")


class InquiryResponse(BaseModel):
    userId: str = Field(..., description="Unique identifier for the user")
    original_message: str = Field(..., description="The original message sent by the user")
    sanitized_message: str = Field(..., description="The message after PII has been sanitized")
    redactions_found: list[str] = Field(..., description="List of PII types that were redacted from the original message")
    generated_answer: str = Field(..., description="The answer generated by the AI")
    audit_id: str = Field(..., description="Unique identifier for the audit entry")